// Định nghĩa các thuật ngữ để sử dụng thống nhất
#let thuat-ngu = (
  "te-bao": ("Tế bào", "Cell"),
  "mo": ("Mô", "Tissue"),
  "ad": ("ADN", "DNA"),
  "co-quan": ("Cơ quan", "Organ"),
  "he-co-quan": ("Hệ cơ quan", "Organ system"),
  "homeostasis": ("Cân bằng nội môi", "Homeostasis"),
  "rct": ("Thử nghiệm đối chứng ngẫu nhiên", "Randomized Controlled Trial - RCT"),
  "nhom-chung": ("Nhóm chứng", "Control group"),
  "ti-the": ("Ti thể", "Mitochondria"),
  "chromatin": ("Chất nhiễm sắc", "Chromatin"),
  "mitosis": ("Nguyên phân", "Mitosis"),
  "meiosis": ("Giảm phân", "Meiosis"),
  "apoptosis": ("Chết theo chương trình", "Apoptosis"),
  "neuron": ("Nơ-ron", "Neuron"),
  "synapse": ("Xi-náp", "Synapse"),
  "he-than-kinh": ("Hệ thần kinh", "Nervous system"),
  "he-than-kinh-tu-chu": ("Hệ thần kinh tự chủ", "Autonomic nervous system"),
  "thuy-truoc-tran": ("Thùy trước trán", "Prefrontal cortex"),
  "hormone": ("Hormone", "Hormone"),
  "noi-tiet": ("Nội tiết", "Endocrine"),
  "tuyen-yen": ("Tuyến yên", "Pituitary gland"),
  "tuyen-giap": ("Tuyến giáp", "Thyroid gland"),
  "tuy-tang": ("Tụy", "Pancreas"),
  "mien-dich": ("Miễn dịch", "Immune system"),
  "khang-the": ("Kháng thể", "Antibody"),
  "vaccine": ("Vắc-xin", "Vaccine"),
  "tu-mien": ("Tự miễn", "Autoimmune"),
  "tim-mach": ("Tim mạch", "Cardiovascular"),
  "ho-hap": ("Hô hấp", "Respiratory"),
  "dong-mach": ("Động mạch", "Artery"),
  "tinh-mach": ("Tĩnh mạch", "Vein"),
  "hong-cau": ("Hồng cầu", "Red blood cell"),
  "huyet-ap": ("Huyết áp", "Blood pressure"),
  "tieu-hoa": ("Tiêu hóa", "Digestive"),
  "vi-sinh": ("Hệ vi sinh vật", "Microbiome"),
  "gan": ("Gan", "Liver"),
  "ruot-non": ("Ruột non", "Small intestine"),
  "chuyen-hoa": ("Chuyển hóa", "Metabolism"),
  "di-truyen": ("Di truyền", "Genetics"),
  "gene": ("Gene", "Gene"),
  "nhiem-sac-the": ("Nhiễm sắc thể", "Chromosome"),
  "dot-bien": ("Đột biến", "Mutation"),
  "nhan-thuc": ("Nhận thức", "Cognition"),
  "y-thuc": ("Ý thức", "Consciousness"),
  "tri-nho": ("Trí nhớ", "Memory"),
  "giac-ngu": ("Giấc ngủ", "Sleep"),
  "lao-hoa": ("Lão hóa", "Aging"),
  "benh-tat": ("Bệnh tật", "Disease"),
  "suc-khoe": ("Sức khỏe", "Health"),
  "kinh-mach": ("Kinh mạch", "Meridian"),
  "khi": ("Khí", "Qi"),
  "huyet": ("Huyệt", "Acupoint"),
  "khi-cong": ("Khí công", "Qigong"),
  "am-duong": ("Âm-Dương", "Yin-Yang"),
  "ngu-hanh": ("Ngũ hành", "Five Elements"),
  "khi-huyet": ("Khí huyết", "Qi and Blood"),
)

// Hàm hiển thị thuật ngữ
#let term(key) = {
  if key in thuat-ngu {
    thuat-ngu.at(key).at(0)
  } else {
    "[" + key + "]"
  }
}
