#!/bin/bash
# Build script for HumanBodyScience book
# Creates versioned PDFs with changelog

set -e

# Configuration
BOOK_NAME="HumanBodyScience"
BUILD_DIR="downloads"
CHANGELOG_FILE="$BUILD_DIR/changelog.txt"
TOTAL_FIGURES=$(grep -r "#figure" chapters/*.typ | wc -l | tr -d ' ')
TOTAL_CONTENT_CHAPTERS=$(find chapters -maxdepth 1 -type f -name '[0-9][0-9]-*.typ' ! -name '99-*' | wc -l | tr -d ' ')

# Create downloads directory if not exists
mkdir -p "$BUILD_DIR"

# Generate version string: YYYY.MM.DD.HHMM
VERSION=$(date +"%Y.%m.%d.%H%M")
OUTPUT_FILE="$BUILD_DIR/${BOOK_NAME}.${VERSION}.pdf"

echo "================================================"
echo "Building HumanBodyScience v$VERSION"
echo "================================================"

# Create temporary metadata file with version
cat > config/build_metadata.typ << EOF
// Auto-generated by build.sh - Do not edit manually
#let build-timestamp = "$VERSION"
#let build-date = "$(date +"%d/%m/%Y")"
#let build-time = "$(date +"%H:%M:%S")"
EOF

# Compile the book
echo "Compiling PDF..."
typst compile main.typ "$OUTPUT_FILE"

if [ $? -eq 0 ]; then
    FILE_SIZE=$(ls -lh "$OUTPUT_FILE" | awk '{print $5}')
    echo "✓ Build successful: $OUTPUT_FILE ($FILE_SIZE)"
    
    # Update changelog
    echo "Updating changelog..."
    
    # Create header if file doesn't exist
    if [ ! -f "$CHANGELOG_FILE" ]; then
        cat > "$CHANGELOG_FILE" << 'EOF'
# CHANGELOG - Khoa học về cơ thể người
# Lịch sử các phiên bản xuất bản

EOF
    fi
    
    # Add new entry at the top (after header)
    TEMP_FILE=$(mktemp)
    
    # Get first 3 lines (header)
    head -n 3 "$CHANGELOG_FILE" > "$TEMP_FILE"
    
    # Add new version info
    cat >> "$TEMP_FILE" << EOF

## Phiên bản $VERSION ($(date +"%d/%m/%Y %H:%M"))

### Thông tin file
- Tên file: ${BOOK_NAME}.${VERSION}.pdf
- Kích thước: $FILE_SIZE
- Biên dịch: $(date +"%d/%m/%Y lúc %H:%M:%S")

### Thay đổi
- [Tự động] Build thành công
- Tổng số hình: $TOTAL_FIGURES
- Tổng số chương nội dung: $TOTAL_CONTENT_CHAPTERS

EOF
    
    # Append old entries (skip first 3 lines)
    tail -n +4 "$CHANGELOG_FILE" >> "$TEMP_FILE"
    
    mv "$TEMP_FILE" "$CHANGELOG_FILE"
    
    echo "✓ Changelog updated"
    
    # Create latest symlink
    cd "$BUILD_DIR"
    ln -sf "${BOOK_NAME}.${VERSION}.pdf" "${BOOK_NAME}.latest.pdf"
    cd ..
    
    echo "✓ Created symlink: ${BOOK_NAME}.latest.pdf -> ${BOOK_NAME}.${VERSION}.pdf"
    
    echo ""
    echo "================================================"
    echo "Build Summary"
    echo "================================================"
    echo "Version:  $VERSION"
    echo "Output:   $OUTPUT_FILE"
    echo "Size:     $FILE_SIZE"
    echo "Symlink:  $BUILD_DIR/${BOOK_NAME}.latest.pdf"
    echo "================================================"
    
    # Show recent versions
    echo ""
    echo "Recent versions:"
    ls -lht "$BUILD_DIR"/*.pdf | head -5
    
else
    echo "✗ Build failed!"
    exit 1
fi
